server:
  port: 8081

spring:
  application:
    name: analytics-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5433/analytics-db
      driver-class-name: org.postgresql.Driver
      username: egor
      password: fusion

    clickhouse:
      url: jdbc:ch://localhost:8123/analyticdb
      username: egor
      password: fusion
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 600000
        connection-timeout: 30000
  #    jpa:
  #

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.jdbc.core: DEBUG